# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy website

on:
    workflow_dispatch:
        inputs:
            deploy-path:
                description: "Location to deploy"
                required: true
                type: choice
                default: francis
                options:
                    - triathlondetoulouse/master/public
                    - francis
            deploy-environment:
                description: "Environment to deploy"
                required: true
                type: choice
                default: production
                options:
                    - production
                    - development
            git-ref:
                description: "Git ref (branch, sha, tag) to deploy"
                required: true
                type: string
                default: master

jobs:
    build-and-test:
        name: Build and test
        runs-on: ubuntu-latest

        steps:
            - name: Checkout ${{ github.event.inputs.git-ref }}
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.event.inputs.git-ref }}

            - name: Read .nvmrc
              id: read-nvmrc
              run: echo node-version=$(cat .nvmrc) >> $GITHUB_OUTPUT

            - name: Use Node.js version from .nvmrc
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ steps.read-nvmrc.outputs.node-version }}
                  cache: 'yarn'

            - name: Install dependencies
              run: yarn install --immutable

            - name: Build
              if: ${{ github.event.inputs.deploy-environment == 'production' || github.event.inputs.deploy-path == 'triathlondetoulouse/master/public' }}
              run: yarn build

            - name: Build dev mode
              if: ${{ github.event.inputs.deploy-environment == 'development' }}
              run: yarn build --configuration development

            - name: Backup web
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.SERVER_HOST }}
                username: ${{ secrets.SERVER_USERNAME }}
                password: ${{ secrets.SERVER_PASSWORD }}
                script: ./create_backup.sh ${{ github.event.inputs.deploy-path }}

            - name: build archive
              run: |
                tar -czf build_${{ github.sha }}.tar.gz --exclude="assets" -C ./dist/frontend .
                echo "Archive created: build_${{ github.sha }}.tar.gz"

            - name: upload file
              uses: appleboy/scp-action@master
              with:
                host: ${{ secrets.SERVER_HOST }}
                username: ${{ secrets.SERVER_USERNAME }}
                password: ${{ secrets.SERVER_PASSWORD }}
                source: build_${{ github.sha }}.tar.gz
                target: "backup"

            - name: Deploy
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.SERVER_HOST }}
                username: ${{ secrets.SERVER_USERNAME }}
                password: ${{ secrets.SERVER_PASSWORD }}
                script: ./deploy_backup.sh build_${{ github.sha }}.tar.gz ${{ github.event.inputs.deploy-path }}
